# This is a basic workflow to help you get started with Actions

name: goreleaser

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Codecov Action
      uses: Atrox/codecov-action@v0.1.3

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v2.1.1

